\set ON_ERROR_STOP on
\getenv identity_password IDENTITY_DB_PASSWORD
\getenv game_password GAME_DB_PASSWORD
CREATE ROLE uno_identity LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'identity_password';
CREATE ROLE uno_game LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'game_password';
CREATE DATABASE uno_identity OWNER uno_identity;
CREATE DATABASE uno_game OWNER uno_game;
REVOKE ALL ON DATABASE uno_identity FROM PUBLIC;
REVOKE ALL ON DATABASE uno_game FROM PUBLIC;
REVOKE CONNECT ON DATABASE uno FROM PUBLIC;
\connect uno_identity
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
\connect uno_game
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
